name: Checks - Product Listing

on:
  pull_request:
    branches:
      - master
    paths:
      - "product-listing/**"

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./product-listing
    steps:
      - uses: actions/checkout@v3
      - name: Linting with Black
        run: |
          pip install black
          black --check .
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.13
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install
      - name: Run tests
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_PRODUCT_LISTING_TABLE_NAME: ${{ secrets.AWS_PRODUCT_LISTING_TABLE_NAME }}
          AWS_API_GATEWAY_URL: ${{ secrets.AWS_API_GATEWAY_URL }}
          SERVICE_USERNAME: ${{ secrets.SERVICE_USERNAME }}
          SERVICE_PASSWORD: ${{ secrets.SERVICE_PASSWORD }}
        run: |
          pipenv run pytest
