name: CI/CD Pipeline - Shopping Cart

on:
  push:
    branches:
      - master
    paths:
      - "shopping-cart/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./shopping-cart
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.13
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install
      - name: Zip files and packages
        run: |
          SITE_PACKAGES=$(pipenv --venv)/lib/python3.9/site-packages
          DIR=$(pwd)/..
          mkdir -p $DIR/shopping-cart/python
          cd $SITE_PACKAGES
          cp -r * $DIR/shopping-cart/python
          cd $DIR/shopping-cart
          zip -FSr9 $DIR/infra/shopping-cart-layer.zip python
          cd $DIR/shopping-cart
          zip -FSr9 $DIR/infra/shopping-cart.zip app
      - name: Upload layer zip file artifact
        uses: actions/upload-artifact@v3
        with:
          name: shopping-cart-layer
          path: infra/shopping-cart-layer.zip
      - name: Upload function zip file artifact
        uses: actions/upload-artifact@v3
        with:
          name: shopping-cart
          path: infra/shopping-cart.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: ./infra
    steps:
      - uses: actions/checkout@v3
      - name: Download layer zip file artifact
        uses: actions/download-artifact@v3
        with:
          name: shopping-cart-layer
      - name: Download function zip file artifact
        uses: actions/download-artifact@v3
        with:
          name: shopping-cart
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy stack
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SHOPPING_CART_LAMBDA_ARN: ${{ secrets.AWS_SHOPPING_CART_LAMBDA_ARN }}
          AWS_SHOPPING_CART_TABLE_NAME: ${{ secrets.AWS_SHOPPING_CART_TABLE_NAME }}
          AWS_API_GATEWAY_URL: ${{ secrets.AWS_API_GATEWAY_URL }}
        run: |
          npm install -g aws-cdk
          npm install
          cd ..
          mv -f shopping-cart.zip infra/shopping-cart.zip
          mv -f shopping-cart-layer.zip infra/shopping-cart-layer.zip
          cd infra
          aws lambda update-function-code --function-name $AWS_SHOPPING_CART_LAMBDA_ARN --zip-file fileb://shopping-cart.zip
          aws lambda publish-layer-version --layer-name shopping-cart --zip-file fileb://shopping-cart-layer.zip
          LAYER_ARN=$(aws lambda list-layer-versions --layer-name shopping-cart --query 'LayerVersions[0].LayerVersionArn' --output text)
          aws lambda update-function-configuration --function-name $AWS_SHOPPING_CART_LAMBDA_ARN --layers $LAYER_ARN --handler app.shopping_cart_controller.handler --environment "Variables={AWS_ACCESS_KEY_ID_LAMBDA=$AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY_LAMBDA=$AWS_SECRET_ACCESS_KEY,AWS_SHOPPING_CART_TABLE_NAME=$AWS_SHOPPING_CART_TABLE_NAME, AWS_API_GATEWAY_URL=$AWS_API_GATEWAY_URL}"